apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sample
  namespace: minikube
  labels:
    app: node-sample
spec:
  replicas: 1 # Number of pod replicas
  selector:
    matchLabels:
      app: node-hello-sample
  template:
    metadata:
      labels:
        app: node-hello-sample
    spec:
      containers:
        - name: node-hello-sample
          image: ausaf0909/node-sample:master-e1bf314c80771907d7b6899cc79acfa79577055d # Replace with your actual Docker image and tag
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
  namespace: minikube
spec:
  selector:
    app: node-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  template:
    spec:
      containers:
        - image: ausaf0909/node-sample:master-e1bf314c80771907d7b6899cc79acfa79577055d
