apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sample
  namespace: minikube
  labels:
    app: node-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-sample
  template:
    metadata:
      labels:
        app: node-hello-sample
    spec:
      containers:
        - name: node-hello-sample
          image: ausaf0909/node-sample:master-7f572cc0267527c3354a64624cd028da08b3e76d # Replace with your actual Docker image and tag
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
