apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sample
  namespace: minikube
  labels:
    app: node-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-sample
  template:
    metadata:
      labels:
        app: node-hello-sample
    spec:
      containers:
        - name: node-hello-sample
          image: ausaf0909/node-sample:master-288d4bd99a400c807ce1760f59874618939843a7 # Replace with your actual Docker image and tag
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-sample
  namespace: minikube
spec:
  selector:
    app: node-hello-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  template:
    spec:
      containers:
        - image: ausaf0909/node-sample:master-288d4bd99a400c807ce1760f59874618939843a7
