apiVersion: v1
kind: Service
metadata:
  name: node-sample
  namespace: minikube
spec:
  selector:
    app: node-hello-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  template:
    spec:
      containers:
        - image: ausaf0909/node-sample:master-9978e265b9dd278df3535e48ddd5adbb1aa18abb