name: Test Action

on:
  workflow_dispatch:
  # push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set environment variables
        run: echo "GITHUB_BRANCH=$(echo $GITHUB
